package com.example.demo1.controller;

import com.example.demo1.model.User;
import com.example.demo1.repositories.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/api/User") // This means URL's start with /demo (after Application path)
public class UserController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

//    @PostMapping(path="/add")
//    public @ResponseBody String addNewUser (@RequestParam(value = "String") String name, @RequestParam(value = "email") String email) {
//        User n = new User();
//        n.setName(name);
//        n.setEmail(email);
//        userRepository.save(n);
//        return "Save";
//    }

//    @Autowired
//    private UserService userService;
//
//
//    @PostMapping("/add")
//    public User addDetailUser(@RequestBody User user){
//        return userService.addUser(user);
//    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}